export const currencies = [
    // Priority Currencies
    { value: 'NGN', label: 'NGN (₦)' },
    { value: 'USD', label: 'USD ($)' },
    { value: 'GBP', label: 'GBP (£)' },

    // Other Currencies (Alphabetical)
    { value: 'AED', label: 'AED (د.إ)' },
    { value: 'AOA', label: 'AOA (Kz)' },
    { value: 'AUD', label: 'AUD ($)' },
    { value: 'BRL', label: 'BRL (R$)' },
    { value: 'BWP', label: 'BWP (P)' },
    { value: 'CAD', label: 'CAD ($)' },
    { value: 'CHF', label: 'CHF (CHF)' },
    { value: 'CNY', label: 'CNY (¥)' },
    { value: 'DZD', label: 'DZD (DA)' },
    { value: 'EGP', label: 'EGP (E£)' },
    { value: 'ETB', label: 'ETB (Br)' },
    { value: 'EUR', label: 'EUR (€)' },
    { value: 'GHS', label: 'GHS (₵)' },
    { value: 'HKD', label: 'HKD ($)' },
    { value: 'IDR', label: 'IDR (Rp)' },
    { value: 'ILS', label: 'ILS (₪)' },
    { value: 'INR', label: 'INR (₹)' },
    { value: 'JPY', label: 'JPY (¥)' },
    { value: 'KES', label: 'KES (KSh)' },
    { value: 'KRW', label: 'KRW (₩)' },
    { value: 'MAD', label: 'MAD (DH)' },
    { value: 'MYR', label: 'MYR (RM)' },
    { value: 'NAD', label: 'NAD ($)' },
    { value: 'PHP', label: 'PHP (₱)' },
    { value: 'QAR', label: 'QAR (﷼)' },
    { value: 'RUB', label: 'RUB (₽)' },
    { value: 'RWF', label: 'RWF (FRw)' },
    { value: 'SAR', label: 'SAR (﷼)' },
    { value: 'SGD', label: 'SGD ($)' },
    { value: 'THB', label: 'THB (฿)' },
    { value: 'TRY', label: 'TRY (₺)' },
    { value: 'TZS', label: 'TZS (TSh)' },
    { value: 'UGX', label: 'UGX (USh)' },
    { value: 'VND', label: 'VND (₫)' },
    { value: 'XAF', label: 'XAF (CFA)' },
    { value: 'XOF', label: 'XOF (CFA)' },
    { value: 'ZAR', label: 'ZAR (R)' },
    { value: 'ZMW', label: 'ZMW (ZK)' },
] as const;

export type CurrencyCode = typeof currencies[number]['value'];
