#!/usr/bin/env python3
"""Refloww icon builder: SVG (mono + duotone), PNG, sprite, JSON, React components, CSS.
Usage: python3 build.py [outdir]
"""
import os, sys, json, shutil, cairosvg
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import defs1, defs2, defs3
from core import REG, ALIAS, GROUP, pascal, svg_file, render_els, SW

OUT = sys.argv[1] if len(sys.argv) > 1 else 'out/refloww-icons'
INK, ORANGE, WHITE = '#2d3748', '#fc6d2d', '#ffffff'
PNG_PX = 256

for sub in ['svg/mono','svg/duotone','png/duotone','png/mono','png/mono-white','react/icons','preview']:
    os.makedirs(os.path.join(OUT, sub), exist_ok=True)

names = list(REG)

# ---------- SVG + PNG ----------
for n in names:
    open(f'{OUT}/svg/mono/{n}.svg','w').write(svg_file(n,'currentColor',None)+'\n')
    open(f'{OUT}/svg/duotone/{n}.svg','w').write(svg_file(n,INK,ORANGE)+'\n')
    for folder,(b,a) in {'duotone':(INK,ORANGE),'mono':(INK,INK),'mono-white':(WHITE,WHITE)}.items():
        svg = svg_file(n,b,a,size=24)
        cairosvg.svg2png(bytestring=svg.encode(), write_to=f'{OUT}/png/{folder}/{n}.png', output_width=PNG_PX, output_height=PNG_PX)

# ---------- sprite ----------
sym = []
for n in names:
    inner = render_els(REG[n],'react','currentColor','currentColor')
    # sprite uses plain SVG attrs (not JSX): convert the JSX style objects
    inner = inner.replace('style={{stroke:"var(--rf-accent, currentColor)"}}','style="stroke:var(--rf-accent,currentColor)"')
    inner = inner.replace('style={{fill:"var(--rf-accent, currentColor)"}}','style="fill:var(--rf-accent,currentColor)"')
    inner = inner.replace(' fill="currentColor"',' fill="currentColor"').replace(' className="rf-a"',' class="rf-a"').replace(' pathLength={1}','')
    sym.append(f'<symbol id="rf-{n}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="{SW}" stroke-linecap="round" stroke-linejoin="round">{inner}</symbol>')
open(f'{OUT}/sprite.svg','w').write('<svg xmlns="http://www.w3.org/2000/svg" style="display:none">'+''.join(sym)+'</svg>\n')

# ---------- JSON + markdown of svg codes ----------
rev = {}
for a,k in ALIAS.items(): rev.setdefault(k,[]).append(a)
meta = []
for n in names:
    meta.append({'name':n,'component':pascal(n),'group':GROUP[n],'lucideAliases':sorted(rev.get(n,[])),
                 'svg':svg_file(n,'currentColor',None)})
json.dump(meta, open(f'{OUT}/icons.json','w'), indent=1)

md = ['# Refloww icons — SVG codes\n','24×24 · stroke 1.75 · round caps/joins · `currentColor`. Accent parts inherit `currentColor` unless `--rf-accent` is set (see README).\n']
cur=None
for m in meta:
    if m['group']!=cur:
        cur=m['group']; md.append(f'\n## {cur}\n')
    al = (' — replaces Lucide: '+', '.join(f'`{a}`' for a in m['lucideAliases'])) if m['lucideAliases'] else ''
    md.append(f"### `{m['component']}`{al}\n```svg\n{m['svg']}\n```\n")
open(f'{OUT}/svg-codes.md','w').write('\n'.join(md))

# ---------- React ----------
tsx = ['// AUTO-GENERATED by scripts/refloww-icons/build.py — edit the defs, not this file.',
       "import { createIcon } from './createIcon';",'']
exports = []
for n in names:
    inner = render_els(REG[n],'react','currentColor','currentColor')
    # pathLength lets the accent stroke "draw on" with CSS (.rf-draw)
    inner = inner.replace(' className="rf-a"',' className="rf-a" pathLength={1}') if False else inner
    P = pascal(n)
    tsx.append(f"export const {P} = createIcon('{P}', <>{inner}</>);")
    exports.append(P)
tsx.append('')
tsx.append('/* Lucide-compatible aliases so migration is an import swap */')
seen=set(exports)
alias_lines=[]
for a,k in sorted(ALIAS.items()):
    if a in seen: continue
    alias_lines.append(f"export const {a} = {pascal(k)};"); seen.add(a)
tsx += alias_lines
open(f'{OUT}/react/icons/icons.tsx','w').write('\n'.join(tsx)+'\n')

create = '''import { forwardRef, type ReactNode, type SVGProps, type ForwardRefExoticComponent, type RefAttributes } from 'react';

/** Stroke weights. Regular is the house weight; bold is for active/selected states. */
export const ICON_WEIGHT = { light: 1.5, regular: 1.75, bold: 2.25 } as const;

export interface IconProps extends Omit<SVGProps<SVGSVGElement>, 'ref'> {
    size?: number | string;
    /** Overrides weight. Prefer `weight`; avoid ad-hoc numbers. */
    strokeWidth?: number | string;
    weight?: keyof typeof ICON_WEIGHT;
    /** Accessible name. Omit for decorative icons (default: aria-hidden). */
    title?: string;
}

export type IconComponent = ForwardRefExoticComponent<IconProps & RefAttributes<SVGSVGElement>>;

export function createIcon(displayName: string, children: ReactNode): IconComponent {
    const Icon = forwardRef<SVGSVGElement, IconProps>(function Icon(
        { size = 24, strokeWidth, weight = 'regular', className, title, ...rest },
        ref
    ) {
        return (
            <svg
                ref={ref}
                xmlns="http://www.w3.org/2000/svg"
                width={size}
                height={size}
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth={strokeWidth ?? ICON_WEIGHT[weight]}
                strokeLinecap="round"
                strokeLinejoin="round"
                className={className ? `rf-icon ${className}` : 'rf-icon'}
                role={title ? 'img' : undefined}
                aria-hidden={title ? undefined : true}
                {...rest}
            >
                {title ? <title>{title}</title> : null}
                {children}
            </svg>
        );
    });
    Icon.displayName = displayName;
    return Icon;
}
'''
open(f'{OUT}/react/icons/createIcon.tsx','w').write(create)

allnames = sorted(seen)
reg = ['// AUTO-GENERATED — name → component map for string-based icon references',
       "// (e.g. documentTypes.ts / fieldTypes.ts use icon: 'FileText').",
       "import type { IconComponent } from './createIcon';",
       "import * as I from './icons';",'',
       'export const iconRegistry: Record<string, IconComponent> = {']
for a in allnames: reg.append(f"    {a}: I.{a},")
reg.append('};'); reg.append('')
reg.append("export type IconName = keyof typeof iconRegistry;")
open(f'{OUT}/react/icons/registry.ts','w').write('\n'.join(reg)+'\n')

iconcmp = '''import { iconRegistry, type IconName } from './registry';
import type { IconProps } from './createIcon';

/** Resolve an icon from a string name, e.g. <Icon name="Invoice" className="w-4 h-4" /> */
export function Icon({ name, ...props }: { name: IconName | (string & {}) } & IconProps) {
    const Cmp = iconRegistry[name];
    return Cmp ? <Cmp {...props} /> : null;
}
'''
open(f'{OUT}/react/icons/Icon.tsx','w').write(iconcmp)

index = '''export * from './icons';
export { Icon } from './Icon';
export { iconRegistry, type IconName } from './registry';
export { createIcon, ICON_WEIGHT, type IconProps, type IconComponent } from './createIcon';
// Drop-in for `import type { LucideIcon } from 'lucide-react'`
export type { IconComponent as LucideIcon } from './createIcon';
'''
open(f'{OUT}/react/icons/index.ts','w').write(index)

print(len(names),'glyphs;',len(allnames),'exported names;', len(os.listdir(f'{OUT}/png/duotone')),'png/set')
